version: '3'
services:
  gocd-server:
    build: .
    container_name: gocd-server
    hostname: gocd
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - ./godata:/godata
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      ["bash", "-c", "chown -R go /godata /var/run/docker.sock && /docker-entrypoint.sh"]
    network_mode: bridge
